@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods


package models {



    package grid {
        class Grid {
            +<<create>>Grid(size:Integer[2])
            -int size
            +changeStateOfTile(x:Integer,y:Integer,state:State)
            +tryPlacingBoat(x:Integer;y:Integer):bool
        }

        interface GridObserver {
            +updateGrid()
        }
        Grid "1" *--> "1..* -observer[]" GridObserver

        class Tile <<abstract>> {
            +<<create>>Tile()
            +set_State(newState:State)
            -notify_observer()
        }

        interface Tile_observer {
            +update_tile(state:State)
        }

        Tile "1" o--> "0..* -list_observer" .models.grid.Tile_observer
        Grid "1" *--> "1..*" Tile : "-TilesMap[]"

    }
    package placeable{

        class Placeable implements .models.grid.Tile_observer {
            +<<create>>Placeable(name:String,position:Integer[2],size:Integer,rotation:bool)
            -size:Integer
            -name:String
            +{abstract}updateTileState(state:State)
        }







    package boats{
        class Boats <<abstract>> extends .models.placeable.Placeable{
            +<<create>>Boats(name:String,size:Integer,tile:TopTile,rotation:bool)
            -is_alive:bool
            +notify_observer(life:bool)
            +{abstract}updateTileState(state:State)
        }

        class Submarine extends Boats{
            +<<create>>Submarine()
        }

        class AircraftCarrier extends Boats{
            +<<create>>AircraftCarrier()
        }

        class Cruiser extends Boats{
            +<<create>>Cruiser
        }

        class Destroyer extends Boats{
            +<<create>>Destroyer()
        }

        class TorpedoBoat extends Boats{
            +<<create>>Torpedo_boat()
        }

        class Boats_observer {
            +notify_life(life:bool)
        }

        Boats "1" -> "1..* -observer[]" Boats_observer


    }

        package trap{
            class Trap <<abstract>> extends .models.placeable.Placeable{
                +<<create>>Trap(int:OwnerId)
                +{abstract}updateTileState(state:State)
                +effect_onHit()
            }

            class Black_hole extends Trap{
                +<<create>>BlackHole(int:OwnerId)
                -name:String
                +update_tile(tile:Tile)
                +effect_onHit()
            }
            Black_hole ->.Controllers.GameController :<<use>>

            class Tornado extends Trap{
                +<<create>>Tornado(int:OwnerId)
                -name:String
                +update_tile(tile:Tile)
                +effect_onHit()
            }
            Tornado ->GameController :<<use>>
        }





        class PlaceableFactory{
            +<<create>>PlaceableFactory()
            +createCruiser():Boats
            +createDestroyer():Boats
            +createTorpedoBoat():Boats
            +createSubmarine():Boats
            +createAircraftCarrier():Boats
        }


        PlaceableFactory ..> boats.Cruiser : <<uses>>
        PlaceableFactory ..> boats.Destroyer : <<uses>>
        PlaceableFactory ..> boats.TorpedoBoat : <<uses>>
        PlaceableFactory ..> boats.Submarine : <<uses>>
        PlaceableFactory ..> boats.AircraftCarrier : <<uses>>

        PlaceableFactory ..> trap.Tornado : <<uses>>
        PlaceableFactory ..> trap.Black_hole : <<uses>>



        }





    package state{

        Enum StateName{

        }


        interface State {
            getCurrentState():StateName
            +onHit():State
        }
        StateName<-- State :-currentState

        package unusedTiles{

        class Boat_tile implements .models.state.State{
            +<<create>> Boat_tile()
            +onHit():Boat_hit_tile
        }

        class Empty_tile implements .models.state.State{
            +<<create>> Empty_tile()
            +onHit():Miss_Tile
        }

        class Island_tile implements .models.state.State{
            +<<create>> Island_tile()
            +onHit():Island_Searched_tile

        }

        class Trap_tile implements .models.state.State{
            +<<create>> Trap_tile()
            +onHit():Trap_used_tile
        }


        }

        package usedTiles{

        class Boat_hit_tile implements .models.state.State{
            +<<create>> Boat_tile()
            +onHit():null
        }

       class Miss_tile implements .models.state.State{
           +<<create>> Miss_tile()
           +onHit():null
       }

        class Island_Searched_tile implements .models.state.State{
            +<<create>> Island_Searched_tile()
            +onHit():null
        }

        class Trap_used_tile implements .models.state.State{
            +<<create>> Trap_tile()
            +onHit():null
        }

        }










    }

    Tile "select" *-right-> "1 -state" state.State



    package player{
        class Player <<abstract>> implements models.placeable.boats.Boats_observer{
            +<<create>>Player(grid:Grid)
            -id:Integer
            -isAlive :bool
            +addBoat(boat:Boat)
            +addTrap(trap:Trap)
            +reactToDeathOfBoat(live:Bool)
        }

        class AI extends Player{
            +<<create>>AI()
            +randomPlace()
        }

        class HumanPlayer extends Player{
            +<<create>>HumanPlayer()
        }

        Player "*"o-->"1 -playerGrid" models.grid.Grid
        Player "*"*-->"* -playerBoats[]" models.placeable.boats.Boats
        .Controllers.PlacementController ..> models.placeable.PlaceableFactory : <<use>>
        Player "*"*--> "2 -playerTraps[]" models.placeable.trap.Trap
    }

    package weapon{
            enum EffectType {
                HIT=1
                SCAN=0
            }
            class Effect{
                +<<create>>Effect(x:Integer,y:Integer,effect:EffectType)
                -x: Integer
                -y: Integer
                +getPos():Integer[]
                +getDamage():Integer
            }
            interface Weapon {
                +use(x:Integer, y:Integer):Effect[]
            }

            class Missile implements Weapon {
                +use(x, y):Effect[]
            }

            class Bomber implements Weapon {
                +use(x, y):Effect[]
            }

            class Sonar implements Weapon {
                +use(x, y):Effect[]
            }
            Effect *-->"1 -effect" EffectType
            Weapon "1" ..> "*" Effect : <<returns>>

        }

}

package Controllers #A0F {

    interface GameController{
        +<<create>>GameController()
        +startGame()
        +endGame()
        +requestAttack(attackerID:Integer,x:Integer,y:Integer,weapon:Weapon)
    }

    class ConcreteGameController implements GameController{
        +<<create>>GameController()
        +requestAttack(attackerID:Integer,x:Integer,y:Integer,weapon:Weapon)
        +attackPlayer(player:PlayerController,x:Integer,y:Integer,weapon:Weapon)
    }

    class GridController {
        +<<create>>GridController(grid:Grid)
        +onHit(x,y,weapon:Weapon)
        +placeBoat(lstTiles : Integer[]) :bool
    }

    class PlayerController{
        +<<create>>PlayerController()
        +setPlayer(player:Player)
        +addBoat(boat:Boat)
        +attack(x:Integer,y:Integer,weapon:Weapon)
        +getAttacked(x:Integer;y:Integer;weapon:Weapon)
        +chooseWeapon(weapon:Weapon)
    }

    PlayerController "1" *-> "1 -player" .models.player.Player
    PlayerController "1" --> "1 -gameController" GameController
    PlayerController "1" *-left-> "1 -gridController" GridController
    ConcreteGameController "1" o--> "2 \n -playerControllers" PlayerController
    GridController "1" .left.> .models.weapon.Weapon:<<use>>



    class PlacementController{
        +<<create>>PlacementController()
        +startPlacement()

    }

    PlacementController ..> GridController :<<use>>



}

package views {
    class UI implements models.grid.GridObserver {
    }
}

GridController "1" o--> "1 -grid" models.grid.Grid
UI "1" *--> "1" Controllers.PlayerController : "\t 2 \n -playerControllers"

@enduml
